# Site settings
title: Puddleglum Jekyll Test
email: my-email@whatever.com
description: > # this means to ignore newlines until "baseurl:"
  This is the site description
baseurl: "" # the subpath of your site, e.g. /blog/

#url: "http://yourdomain.com" # the base hostname & protocol for your site
url: "http://192.168.0.254" # the base hostname & protocol for your site

# MW: Commenting these two out, Aug 27
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
